version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:5000"
    container_name: flask_app
    environment:
      - PYTHONUNBUFFERED=1
      - DB_HOST=mysql.cki101
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=cki101_db
    depends_on:
      - db

  db:
    image: mysql:8.4
    container_name: mysql.cki101
    ports:
      - "8625:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=cki101_db
    volumes:
      - ./db_data:/var/lib/mysql
